# 러너의 게이트 앵커링 조인(대장 로드 -> 구간별 합산 -> state JSON)을 cscript 로 실행해 검사한다
"""`state.demand.urban_volume_vph_by_gate` 생산자 쪽 행동 검사.

문자열 대조가 아니라 **실제로 실행**한다. 러너에서 프로시저를 떼어 harness 로 묶고
가짜 대장 CSV 를 물린 뒤 cscript 로 돌린다. 조인이 틀리면 여기서 잡힌다.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

try:
    from .test_b1a_vbs_verified_capture_static import SOURCE, procedure
except ImportError:  # 모듈로 직접 실행할 때
    from scripts.tests.test_b1a_vbs_verified_capture_static import SOURCE, procedure

CSCRIPT = shutil.which("cscript.exe") or shutil.which("cscript")

PROCEDURES = (
    "LoadUrbanInputGateMap",
    "GateMapField",
    "AddUrbanGateDemand",
    "AddDemandScheduleValue",
    "AddDictNumber",
    "DictValue",
    "UrbanGateDemandJson",
    "UrbanDemandBucketAtSimSec",
    "ActiveDemandScheduleKey",
    "JsonEscape",
    "Num",
    "ToDbl",
)

# 게이트 2개 + 내부발생 1개 + 격자에 없는 1개 + 대장에 아예 없는 1개.
MAP_CSV = """# generated by test
no,gate,status,leg,leg_source,model_node,link,entry_class,role,first_volume_vph,peak_volume_vph,name
11,in_SC1_S,mapped,S,name_suffix,SC1,364,named,urban_input,100.0000,150.0000,가_NB
12,in_SC2_E,mapped,E,name_suffix,SC2,55,named,urban_input,200.0000,300.0000,"나,다_WB"
13,,internal,,,SC3,21,dummy,urban_input,10.0000,15.0000,Dummy Link 1
14,,leg_absent_at_node,SW,link_geometry,SC4,69,unnamed,urban_input,7.0000,9.0000,
"""


def harness_source(map_path: Path) -> str:
    helpers = "\n\n".join(procedure(SOURCE, name) for name in PROCEDURES)
    escaped = str(map_path).replace('"', '""')
    return rf'''Option Explicit
Dim fso, failures, demandScheduleLoaded, demandUrbanBySec, demandFreewayBySec
Dim demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec
Set fso = CreateObject("Scripting.FileSystemObject")
failures = 0
demandScheduleLoaded = True
Set demandUrbanBySec = CreateObject("Scripting.Dictionary")
Set demandFreewayBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanGateBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanUnmappedBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanInternalBySec = CreateObject("Scripting.Dictionary")

{helpers}

Sub Check(condition, label)
    If Not CBool(condition) Then
        failures = failures + 1
        WScript.Echo "FAIL=" & CStr(label)
    End If
End Sub

Sub CheckEqual(actual, expected, label)
    If CStr(actual) <> CStr(expected) Then
        failures = failures + 1
        WScript.Echo "FAIL=" & CStr(label) & " actual=" & CStr(actual) & " expected=" & CStr(expected)
    End If
End Sub

Dim gateMap, entry
Set gateMap = LoadUrbanInputGateMap("{escaped}")
CheckEqual gateMap.Count, 4, "map_rows"
CheckEqual gateMap("11"), "mapped|in_SC1_S", "map_row_11"
CheckEqual gateMap("12"), "mapped|in_SC2_E", "map_row_12"
CheckEqual gateMap("13"), "internal|", "map_row_13"
CheckEqual gateMap("14"), "leg_absent_at_node|", "map_row_14"
CheckEqual GateMapField("mapped|in_SC1_S", 0), "mapped", "field_status"
CheckEqual GateMapField("mapped|in_SC1_S", 1), "in_SC1_S", "field_gate"

' 구간 0 과 900 두 개. 대장에 없는 유입 99 는 unmapped 로 떨어져야 한다.
Dim secKey
For Each secKey In Array("0", "900")
    demandUrbanBySec(secKey) = 1.0
    AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, secKey, gateMap, "11", 100.0
    AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, secKey, gateMap, "12", 200.0
    AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, secKey, gateMap, "13", 10.0
    AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, secKey, gateMap, "14", 7.0
    AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, secKey, gateMap, "99", 3.0
Next
' 같은 게이트에 두 유입이 붙으면 합쳐진다 (leg 병합).
AddUrbanGateDemand demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec, "900", gateMap, "11", 5.0

CheckEqual UrbanGateDemandJson(0), "{{""in_SC1_S"": 100.000000, ""in_SC2_E"": 200.000000}}", "json_sec0"
CheckEqual UrbanGateDemandJson(1200), "{{""in_SC1_S"": 105.000000, ""in_SC2_E"": 200.000000}}", "json_sec1200"
CheckEqual UrbanDemandBucketAtSimSec(demandUrbanInternalBySec, 0), 10, "internal_sec0"
CheckEqual UrbanDemandBucketAtSimSec(demandUrbanUnmappedBySec, 0), 10, "unmapped_sec0"
CheckEqual UrbanDemandBucketAtSimSec(demandUrbanInternalBySec, 5000), 10, "internal_last_interval"

' 스케줄이 없으면 빈 오브젝트다 - 어댑터가 스칼라 폴백으로 돌아간다.
demandScheduleLoaded = False
CheckEqual UrbanGateDemandJson(0), "{{}}", "json_no_schedule"
CheckEqual UrbanDemandBucketAtSimSec(demandUrbanUnmappedBySec, 0), 0, "bucket_no_schedule"
demandScheduleLoaded = True

' 없는 대장 경로는 빈 사전 + WARN.
Dim missing
Set missing = LoadUrbanInputGateMap("__no_such_gate_map__.csv")
CheckEqual missing.Count, 0, "missing_map_empty"

WScript.Echo "FAILURES=" & CStr(failures)
'''


def demand_line() -> str:
    """러너가 state 에 demand 블록을 쓰는 그 줄. 정확히 하나여야 한다."""
    lines = [line for line in SOURCE.splitlines() if '""demand"": {' in line]
    if len(lines) != 1:
        raise AssertionError(f"expected one demand emit line, found {len(lines)}")
    return lines[0].strip()


def emit_harness_source() -> str:
    """WriteStateJson 의 demand 줄을 **그대로** 떼어 가짜 writer 로 실행한다."""
    helpers = "\n\n".join(
        procedure(SOURCE, name)
        for name in ("UrbanGateDemandJson", "UrbanDemandBucketAtSimSec",
                     "ActiveDemandScheduleKey", "AddDictNumber", "JsonEscape", "Num")
    )
    return rf'''Option Explicit
Dim failures, demandScheduleLoaded, demandUrbanBySec, demandFreewayBySec
Dim demandUrbanGateBySec, demandUrbanUnmappedBySec, demandUrbanInternalBySec
Dim demandForecastProfileName, demandUrbanNow, demandFreewayNow, simSec, ts, gates
failures = 0
demandScheduleLoaded = True
Set demandUrbanBySec = CreateObject("Scripting.Dictionary")
Set demandFreewayBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanGateBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanUnmappedBySec = CreateObject("Scripting.Dictionary")
Set demandUrbanInternalBySec = CreateObject("Scripting.Dictionary")

Class FakeWriter
    Public Sub WriteLine(text)
        WScript.Echo "LINE=" & text
    End Sub
End Class

{helpers}

demandUrbanBySec("0") = 398.35125
demandUrbanGateBySec.Add "0", CreateObject("Scripting.Dictionary")
Set gates = demandUrbanGateBySec("0")
AddDictNumber gates, "in_SC104_E", 1250.48
AddDictNumber gates, "in_SC1_S", 890.4
AddDictNumber demandUrbanUnmappedBySec, "0", 1554.48
AddDictNumber demandUrbanInternalBySec, "0", 1484.0
demandForecastProfileName = "real_world_inpx_time_profile"
demandUrbanNow = 398.35125
demandFreewayNow = 3080.0
simSec = 0
Set ts = New FakeWriter
{demand_line()}
'''


@unittest.skipIf(CSCRIPT is None, "cscript.exe not available")
class UrbanGateDemandVbsBehaviorTests(unittest.TestCase):
    def test_emitted_demand_line_is_valid_json_with_gate_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            harness = Path(tmp) / "emit.vbs"
            harness.write_text(emit_harness_source(), encoding="utf-8")
            proc = subprocess.run(
                [CSCRIPT, "//nologo", "//E:vbscript", str(harness)],
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = proc.stdout + proc.stderr
            self.assertEqual(0, proc.returncode, output)
            emitted = [
                line[len("LINE=") :] for line in output.splitlines() if line.startswith("LINE=")
            ]
            self.assertEqual(1, len(emitted), output)
            parsed = json.loads("{" + emitted[0].strip().rstrip(",") + "}")["demand"]
            self.assertEqual(
                {"in_SC104_E": 1250.48, "in_SC1_S": 890.4},
                parsed["urban_volume_vph_by_gate"],
            )
            self.assertEqual(1554.48, parsed["urban_unmapped_volume_vph"])
            self.assertEqual(1484.0, parsed["urban_internal_volume_vph"])
            self.assertEqual(398.35125, round(parsed["urban_volume_vph"], 5))
            self.assertEqual(0, parsed["ramp_volume_vph"])
            self.assertEqual("real_world_inpx_time_profile", parsed["demand_profile"])

    def test_gate_join_behaviour(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            map_path = root / "gate_map.csv"
            map_path.write_text(MAP_CSV, encoding="utf-8")
            harness = root / "harness.vbs"
            harness.write_text(harness_source(map_path), encoding="utf-8")
            proc = subprocess.run(
                [CSCRIPT, "//nologo", "//E:vbscript", str(harness)],
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = proc.stdout + proc.stderr
            self.assertEqual(0, proc.returncode, output)
            self.assertIn("FAILURES=0", output, output)


if __name__ == "__main__":
    unittest.main()
