from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def csv_ints(values: list[int]) -> str:
    return ",".join(str(v) for v in values)


def vehicle_input_link_no(row: dict[str, Any]) -> int | None:
    raw = row.get("link")
    if raw is None:
        return None
    text = str(raw).strip()
    if not text:
        return None
    digits = "".join(ch for ch in text if ch.isdigit() or ch == "-")
    return int(digits) if digits else None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mapping", default="evaluation/current_inventory/network_mapping.json")
    parser.add_argument("--inventory", default="evaluation/current_inventory/inventory.json")
    parser.add_argument("--out-vbs", default="evaluation/generated/global_state_config.vbs")
    parser.add_argument("--out-json", default="evaluation/generated/global_state_config.json")
    args = parser.parse_args()

    mapping_path = Path(args.mapping)
    inventory_path = Path(args.inventory)
    out_vbs = Path(args.out_vbs)
    out_json = Path(args.out_json)

    mapping = json.loads(mapping_path.read_text(encoding="utf-8"))
    inventory = json.loads(inventory_path.read_text(encoding="utf-8"))

    groups = mapping["global_state_groups"]
    freeway_links = [int(v) for v in groups["freeway_links"]]
    vehicle_inputs = inventory["vehicle_inputs"]
    freeway_input_links = sorted(
        {
            link_no
            for row in vehicle_inputs
            if (link_no := vehicle_input_link_no(row)) in freeway_links
        }
    )

    config = {
        "source_mapping": str(mapping_path),
        "source_inventory": str(inventory_path),
        "urban_links": [int(v) for v in groups["urban_links"]],
        "freeway_links": freeway_links,
        "ramp_links": [int(v) for v in groups["ramp_links"]],
        "boundary_links": [int(v) for v in groups["boundary_links"]],
        "freeway_input_links": freeway_input_links,
    }

    out_vbs.parent.mkdir(parents=True, exist_ok=True)
    out_json.parent.mkdir(parents=True, exist_ok=True)

    out_json.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")
    out_vbs.write_text(
        "\n".join(
            [
                "' Auto-generated by scripts/generate_global_state_config.py.",
                "' Do not edit by hand; regenerate after network_mapping.json changes.",
                f"URBAN_LINKS = \"{csv_ints(config['urban_links'])}\"",
                f"FREEWAY_LINKS = \"{csv_ints(config['freeway_links'])}\"",
                f"RAMP_LINKS = \"{csv_ints(config['ramp_links'])}\"",
                f"BOUNDARY_LINKS = \"{csv_ints(config['boundary_links'])}\"",
                f"FREEWAY_INPUT_LINKS = \"{csv_ints(config['freeway_input_links'])}\"",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(json.dumps(config, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
